/-
  ShadowProof Bridge v25 — De Morgan order-two symmetry on the bilattice
  L = Bool × Bool.

  This file is the standalone Lean witness for the executable Python
  report returned by `shadowproof demorgan-symmetry`.  The Python report
  asserts:

    1. demorgan_swap : Bool × Bool → Bool × Bool , (t, r) ↦ (r, t)
       is an involution (order two);
    2. its only fixed points are (true, true) and (false, false);
    3. it is NOT designation-preserving (swaps (true,false) ↔ (false,true));
    4. the generated automorphism group is Z/2.

  This file proves each of these in Lean 4 / Mathlib.

  The intent is: the runtime report cites this file by path; anyone with
  Lean 4 + Mathlib can build it and re-verify the algebraic claims.
-/

import Mathlib

namespace ShadowProof.DemorganSymmetry

/-- The bilattice carrier as `Bool × Bool` (truth × refutation). -/
abbrev L := Bool × Bool

/-- The four named values used in the rest of the codebase. -/
def topL     : L := (true,  false)   -- classical proof
def bottomL  : L := (false, true)    -- classical refutation
def bothL    : L := (true,  true)    -- designated glut  (⊥⊤_L)
def neitherL : L := (false, false)   -- gap              (n_L)

/-- The De Morgan involution: swap the truth/refutation coordinates. -/
def demorganSwap (x : L) : L := (x.2, x.1)

/-- The swap is involutive. -/
theorem demorganSwap_involutive (x : L) :
    demorganSwap (demorganSwap x) = x := by
  rcases x with ⟨t, r⟩
  rfl

/-- As a function, the swap squares to the identity. -/
theorem demorganSwap_sq_eq_id :
    demorganSwap ∘ demorganSwap = id := by
  funext x; exact demorganSwap_involutive x

/-- `top` and `bottom` are swapped by the De Morgan involution. -/
theorem demorganSwap_top_eq_bottom : demorganSwap topL = bottomL := rfl
theorem demorganSwap_bottom_eq_top : demorganSwap bottomL = topL := rfl

/-- `both` and `neither` are fixed by the De Morgan involution. -/
theorem demorganSwap_both_fixed    : demorganSwap bothL    = bothL    := rfl
theorem demorganSwap_neither_fixed : demorganSwap neitherL = neitherL := rfl

/-- Designation: the truth coordinate (matching `BilatticeValue.designated`). -/
def designated (x : L) : Bool := x.1

/-- The swap is NOT designation-preserving: it sends `top` (designated) to
    `bottom` (not designated). -/
theorem demorganSwap_not_designation_preserving :
    ∃ x : L, designated x ≠ designated (demorganSwap x) := by
  refine ⟨topL, ?_⟩
  -- designated topL = true, designated (demorganSwap topL) = false
  decide

/-- Exhaustive case analysis: the only fixed points of `demorganSwap` are
    `both` and `neither`. -/
theorem demorganSwap_fixed_points (x : L) :
    demorganSwap x = x ↔ x = bothL ∨ x = neitherL := by
  rcases x with ⟨(t | _), (r | _)⟩ <;> decide

/-- The automorphism group generated by `identity` and `demorganSwap` is
    cyclic of order two: composition is fully described by

       id ∘ id  = id          id ∘ swap = swap
       swap ∘ id = swap        swap ∘ swap = id

    All four entries are decided by `rfl`-class reasoning. -/
theorem aut_L_is_Z2 :
    (id : L → L) ∘ id          = id           ∧
    (id : L → L) ∘ demorganSwap = demorganSwap ∧
    demorganSwap ∘ (id : L → L) = demorganSwap ∧
    demorganSwap ∘ demorganSwap = (id : L → L) := by
  refine ⟨?_, ?_, ?_, ?_⟩ <;> funext x <;> simp [demorganSwap_involutive]

end ShadowProof.DemorganSymmetry
